{
  assert.doesNotThrow(() => {
    throw Error("err!");
  });
}
